<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>31.1 - await async</title>
	</head>
	<body>
		<!-- Instructions
Lets change the code below to use async await instead of .then and .catch
Understanding the code
We are faking an API request to a food recipe database.
Here we are requesting for food recipe Ids.
We get an array of Ids once consumed. -->

		<script>
			const getIDs = () =>
				new Promise((resolve, reject) => {
					setTimeout(() => {
						resolve([532, 543, 753, 1, 5]);
					}, 1500);
				});

			// Here we are fetching a recipe with a given Id.
			// We are getting a recipe as an object once consumed.
			const getRecipe = (recipeID) => {
				return new Promise((resolve, reject) => {
					setTimeout(
						(ID) => {
							const recipe = {
								title: "Fres h tomato pasta",
								publisher: "Pinchas Hodadad",
							};
							resolve(`${ID}: ${recipe.title}`);
						},
						1500,
						recipeID
					);
				});
			};
			// Here we are consuming the promise.
			// Getting the Ids, then getting a recipe with the id in the index 2.
			// getIDs()
			// 	.then((IDs) => {
			// 		console.log(IDs);
			// 		return getRecipe(IDs[2]);
			// 	})
			// 	.then((recipe) => {
			// 		console.log(recipe);
			// 	})
			// 	.catch((error) => {
			// 		console.log("It is an error!");
			// 	});
			async function syncMe() {
				let id = await getIDs();
				console.log(id);
				let recipe = await getRecipe(id[2]);
				console.log(recipe);
			}
			syncMe().catch((x) => console.log(x));
		</script>
	</body>
</html>
